# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import status.models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status post', 'verbose_name_plural': 'Status posts'},
        ),
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=status.models.upload_status_image),
        ),
    ]
